const assert=require('node:assert/strict');
const {analyzeGrid}=require('../../local_downscaling.js');
const meta={nx:3,ny:3,dx:0.1,dy:0.1,lo1:14,la1:38};
const base=new Float32Array(9).fill(20);
const policy={radiusKm:40,maxResidual:5,maxCorrection:3,maxSpread:2,min:-60,max:60,elevationToleranceM:250};
const terrain=new Float32Array(9).fill(100);
const points=[{lat:38,lon:14,increment:2,elevationM:100},{lat:37.9,lon:14,increment:2,elevationM:100},{lat:38,lon:14.1,increment:2,elevationM:100}];
const result=analyzeGrid(base,meta,points,policy,terrain);
assert.equal(result.correctedCells,9);
assert.ok(result.grid.every(x=>x>20 && x<22));
assert.ok(base.every(x=>x===20),'Original model must remain immutable');
assert.equal(analyzeGrid(base,meta,points.slice(0,2),policy,terrain).correctedCells,0);
assert.equal(analyzeGrid(base,meta,points,policy,null).correctedCells,0);
assert.equal(analyzeGrid(base,meta,points,policy,new Float32Array(9).fill(1000)).correctedCells,0);
assert.equal(analyzeGrid(base,meta,points.map(p=>({...p,increment:50})),policy,terrain).correctedCells,0);
assert.equal(analyzeGrid(base,meta,points.map((p,i)=>({...p,increment:i===0?-5:5})),policy,terrain).correctedCells,0);
const windPolicy={radiusKm:40,maxResidual:10,maxCorrection:4,maxSpread:4,min:-100,max:100};
assert.ok(analyzeGrid(new Float32Array(9),meta,points.map(p=>({...p,increment:-2})),windPolicy).grid.every(x=>x<0));
console.log('Map downscaling tests passed');
